version: "3.9"

services:
  mysqldb:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    # env_file: ./mv-backend/.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=movies_db
    ports:
      - 3307:3306
    volumes:
      - database:/var/lib/mysql
  backend:
    container_name: server
    build:
      context: ./mv-backend
      dockerfile: TestDockerFile
    env_file: ./mv-backend/.env
    volumes:
      - ./mv-backend:/app
      - /app/node_modules
    ports:
      - 4000:4000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=movies_db
      - DB_PORT=3306
    depends_on:
      - mysqldb
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  database:
